# Root OID for all traps
oidRoot: "1.3.6.1.4.1.12345"

# SNMP trap receivers
receivers:
  - id: "primary"
    host: "192.168.1.100"
    port: 162
    community: "public"
  
  - id: "backup"
    host: "192.168.1.101"
    port: 162
    community: "public"

# Monitoring rules
rules:
  # Current time monitoring
  - id: "currentTime"
    oid: "1.1"
    name: "Current Time"
    type: "string"
    command: "date '+%Y-%m-%d %H:%M:%S'"
    interval: 60
    receivers: ["primary", "backup"]

  # Unix timestamp monitoring
  - id: "unixTimestamp"
    oid: "1.2"
    name: "Unix Timestamp"
    type: "integer"
    command: "date +%s"
    interval: 60
    thresholds:
      warning: 0
      critical: 0
    receivers: ["primary"]

  # Day of week monitoring
  - id: "dayOfWeek"
    oid: "1.3"
    name: "Day of Week"
    type: "string"
    command: "date '+%A'"
    interval: 300
    receivers: ["primary", "backup"]

  # System timezone monitoring
  - id: "timezone"
    oid: "1.4"
    name: "System Timezone"
    type: "string"
    command: "date '+%Z'"
    interval: 300
    receivers: ["primary"] 