name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test SNMP Trap Sender

    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Bun Runtime
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install Dependencies
      run: bun install

    - name: Run Loopback Test
      run: |
        echo "Running SNMP trap sender in loopback mode..."
        timeout 30s bun src/index.js --loopback
      
    - name: Generate OID File
      run: |
        echo "Generating OID file..."
        bun src/index.js --generate-oid test.mib
        if [ ! -f test.mib ]; then
          echo "OID file was not generated!"
          exit 1
        fi
        echo "OID file contents:"
        cat test.mib 