name: Release Binary

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Binary

    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Bun Runtime
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install Dependencies
      run: bun install

    - name: Build Binary
      run: |
        echo "Building standalone binary..."
        bun build ./src/index.js --compile --minify --outfile quick-snmp
        chmod +x quick-snmp

    - name: Build Binary (Cross-Platform)
      run: |
        echo "Building standalone binary..."
        bun build ./src/index.js --compile --minify --target=bun-linux-arm64 --outfile quick-snmp_arm64
        bun build ./src/index.js --compile --minify --target=bun-darwin-arm64 --outfile quick-snmp_osx_arm64

    - name: Test Binary (version)
      run: |
        ./quick-snmp --version

    - name: Test Binary (loopback)
      run: |
        ./quick-snmp --loopback

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: |
          quick-snmp
          quick-snmp_arm64
          quick-snmp_osx_arm64
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
